config/routes.rb
Rails.application.routes.draw do
  root 'vignettes#home'
  namespace :vignettes do
    get "home"
    get "semantic"
    get "jquery"
    get "ajax"
    get "underscore"
    get "api_call"
    get "carmen"
  end
  namespace :api do
    get "covid_locations"
  end
  get 'book/color'
  get 'book/sandbox'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
    def covid_locations
        resp = [
        "@32.7773605,-96.7892601,20.6z", # Farmers Market
        "@32.7883222,-96.8018392,20.76z", # Dallas Museum of Art
        "@32.733353,-97.1094854,20.82z", # UTA Bookstore
        "@32.5655895,-97.1423169,21z", # Taqueria Jalisco, Mansfield
        "@32.5602893,-97.1434716,21z", # Crossfit, Mansfield
        "@32.5535748,-97.1669973,20.95z", # Gallilee Baptist Church, Mansfield
        "@32.7291129,-97.126306,20.36z", # UTA Maverick stadium
        "@32.7505822,-97.331543,21z", # Fort Worth Social Security Administration
        "@30.2705109,-97.7528052,18.98z", # Whole Foods, Austin
        "@32.8989567,-97.0378998,15.41z", # DFW Airport
        "@33.2145814,-97.1302873,20.63z" # Mellow Mushroom, Denton
        ]
        
        render :json => resp
       
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vignettes_controller.rb
class VignettesController < ApplicationController
    def home
    end
    def echo
    end
    def semantic
    end
    def jquery
    end
    def underscore
    end
    def api_call
    end
    def ajax
    end
    def carmen
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/vignettes/echo_helper.rb
module Vignettes::EchoHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Module 4
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/vignettes/api_call.html.haml
:coffeescript
  COVID_SYMPTOMS = ["sore throat", "congestion", "diahhrea", "trouble breathing"]
  SYMPTOMS_STR_1 = "Symptoms: Sore throat, red eyes   ,CONGESTION"
  SYMPTOMS_STR_2 = "Symptoms: Sore throat, Diahhrea, red eyes   ,CONGESTION   ,   trouble breathing, diZZIness"
  SYMPTOMS_ARR_1 = ["sore throat", "diarrhea", "vertigo", "warts", "pale skin", "trouble breathing", "shortness of breath", "high blood pressure"]
  
  # MAIN FUNCTION
  $ ->
    alertify.set('notifier','position', 'top-left')
    
    response1 = problem1(SYMPTOMS_STR_2)
    $('#response').html(response1)
    
    problem2(SYMPTOMS_ARR_1)

    problem3()

  problem1 = (symptoms_string)->
    console.log "PROBLEM1: STRING MANIPULATION"
    result = symptoms_string.split(" ")
    result.splice(0, 1)
    result = result.join(" ")
    result = result.split(",")
    result = _.map(result, (el) => el.trim(" "))
    result = _.map(result, (el) => el.toLowerCase())
    result = _.filter(result, (symptom) => _.contains(COVID_SYMPTOMS, symptom))
    result = result.join("; ")
    console.log result
    return result
    
  problem2 = (symptoms_arr)->
    console.log "PROBLEM2: PROGRAMMATIC DOM"
    rightList = $('.ui.list.ordered.right')
    _.each(symptoms_arr, (symptom) => 
      ListElement = $('<li>')
      ListElement.html(symptom)
      
      rightList.append(ListElement)
    )
    
    return
    
  problem3 = ()->
    API_KEY = "TODO" 
    # TODO
    return
  
  
/ HTML/CSS CODE - DO NOT MODIFY ANYTHING UNDER THIS LINE  
  
:scss
  .panel{
    margin-top: 60px;
  }
  
  .covid{
    font-weight: bold;
    color: blue;
  }

.ui.centered.grid
  .ten.wide.column
    .panel
      #problem-1
        %h1.ui.header.top.attached.blue String Manipulation
        .ui.segment.stacked.attached
          %p#response TODO
      
      %br 
      
      #problem-2
        %h1.ui.header.top.attached.blue Programmatic DOM
        .ui.segment.stacked.attached
          .ui.two.column.stackable.grid.container
            .column
              .ui.header LEFT LIST
              %ol.ui.list.ordered.left
            .column
              .ui.header RIGHT LIST
              %ol.ui.list.ordered.right
      
      %br 
      
      #problem-3
        %h1.ui.header.top.attached.blue Location Resolver
        .ui.segment.stacked.attached
          .ui.two.column.stackable.grid.container
            .column
              .ui.header COVID LOCATIONS
              %ol.ui.list.ordered.left#covid-locations
              / PROGRAMMATIVALLY ADD KNOWN COVID GPS LOCATIONS TO LIST  
            .column
              .ui.header RESOLVED LOCATIONS
              %ol.ui.list.ordered.right#resolved-locations
              / PROGRAMMATIVALLY RESOLVE COVID GPS LOCATIONS TO FORMATTED ADDRESSES
            
          

app/views/vignettes/color.html.haml
          
    
:coffeescript
  window.paper = paper

  $ ->
    window.gui = new dat.GUI()
    
    window.app = new ColoringBook
      canvas: $('#main-canvas')
      name: "MyColoringBook"
      
    alertify.set('notifier','position', 'bottom-left')

  
    
:scss
  html, body, #sandbox{
    width: 100%;
    height: 100%;
    overflow:hidden;
  }
  canvas{
    border: 1px solid blue;
    background: lighten(blue, 40%);
  }


#sandbox
  %canvas{id: "main-canvas", resize: "resize"}

app/views/vignettes/home.html.haml
#directory.ui.raised.very.padded.text.container.segment
    %h1.ui.header Vignette Links
    %ol
        %li= link_to "CSS Frameworks - Semantic", vignettes_semantic_path
        %li= link_to "API", vignettes_api_call_path
    
    

app/views/vignettes/sandbox.html.haml
          
    
:coffeescript
  window.paper = paper

  $ ->
    window.gui = new dat.GUI()
    
    window.app = new PaperJSApp
      canvas: $('#main-canvas')
      name: "MyColoringSandbox"
      
    alertify.set('notifier','position', 'bottom-left')
    sandbox_routine()
    
    
  sandbox_routine = ()->
    c = new paper.Path.Circle
      radius: 50
      fillColor: "red"
      position: paper.view.center
  
    
:scss
  html, body, #sandbox{
    width: 100%;
    height: 100%;
    overflow:hidden;
  }
  canvas{
    border: 1px solid blue;
    background: lighten(blue, 40%);
  }


#sandbox
  %canvas{id: "main-canvas", resize: "resize"}

app/views/vignettes/semantic.html.haml
/ SYMPTOM CHECKER FORM SKELETON
.ui.centered.grid
  .ten.wide.column
    #symptom-checker.panel
      .ui.three.ordered.steps
        .active.step
          .content
            .title Assessment
            .description We'll review your specific symptoms and exposure risk
        .step
          .content
            .title Local Comparison
            .description We'll compare your data against those in your area
        .step
          .content
            .title Sites & More Info
            .description If needed, we will provide you with additional information
      
      %h1.ui.header.top.attached.blue Should I get tested?
      .ui.segment.stacked.attached
        %form#assessment.ui.form
          %h3.ui.attached Have you experienced any of the following symptoms?
          .ui.fitted.divider
          %br
          .inline.field
            .ui.checkbox
              %input.hidden{:tabindex => "0", :type => "checkbox"}/
              %label Aches and pains
          .inline.field
            .ui.checkbox
              %input.hidden{:tabindex => "0", :type => "checkbox"}/
              %label Fever
          .inline.field
            .ui.checkbox
              %input.hidden{:tabindex => "0", :type => "checkbox"}/
              %label Dry cough
          .inline.field
            .ui.checkbox
              %input.hidden{:tabindex => "0", :type => "checkbox"}/
              %label Fatigue
          %h3.segment Exposure assessment
          .ui.fitted.divider
          %br
          .field
            %label Have you had contact with an individual that tested positive for COVID-19?
            .ui.selection.dropdown
              %input{:name => "contact", :type => "hidden"}/
              %i.dropdown.icon
              .default.text Fill out
              .menu
                .item{"data-value" => "0"} No, not to my knowledge.
                .item{"data-value" => "1"} Maybe, I am unsure if I made contact.
                .item{"data-value" => "2"} Yes, I am currently COVID-19 positive or have made contact with somebody who has.
          .field
            %label Did you travel outside your state or country in the last 2-14 days?
            .ui.selection.dropdown
              %input{:name => "travel", :type => "hidden"}/
              %i.dropdown.icon
              .default.text Fill out
              .menu
                .item{"data-value" => "0"} No, I have not traveled.
                .item{"data-value" => "1"} Yes, I have traveled.
          .field
            %label If so, where?
            %input{:name => "where", :placeholder => "State or country of travel", :type => "text"}/
          %br
          %button.ui.primary.button{:type => "submit"} Submit


/ DO NOT MODIFY ANYTHING BELOW THESE LINES
:coffeescript
  $ ->
    $('.dropdown').dropdown()
    
    $('form').submit (event) ->
      console.log "SUBMIT!"
      console.log $(this).serializeArray()
      event.preventDefault()
      return

:scss
  .panel{
    margin-top: 60px;
  }
  